{% set name = "rptools" %}
{% set version = "5.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/rptools/archive/{{ version }}.tar.gz
  sha256: 698d59cd52c12d900c9af34877c2963f75d46ac062051bb33790162fcea3cc56

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - brs_utils
    - cobra
    - rdkit
    - python-libsbml
    - numpy
    - pandas
    - scipy
    - equilibrator-api
    - openbabel
    - colored
    - networkx >=2.5
    - filetype
    - rr_cache
    - rxn_rebuild
    - chemlite
    - h5py
    - xgboost
    - beautifulsoup4
    - sqlalchemy =1.4.31

test:
  source_files:
    - tests
  imports:
    - rptools
  requires:
    - pytest
    - pytest-cov
    - pytest-mock
  commands:
    - python -m rptools --help
    - cd tests
    - pytest -v --cov --cov-report term-missing

about:
  home: https://github.com/brsynth/rptools
  summary: Suite of tools that work on rpSBML data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
